import pandas as pd

# -----------------------------------
# 1. Read the data from CSV file
# -----------------------------------
file_path = "sales_data.csv"   # change path if needed
df = pd.read_csv(file_path)

print("✅ Data loaded successfully!\n")

# -----------------------------------
# 2. Explore basic information
# -----------------------------------
print("🔍 First 5 rows of the dataset:\n")
print(df.head(), "\n")

print("ℹ️ Basic info about the dataset:\n")
print(df.info(), "\n")

print("📊 Basic statistics for numerical columns:\n")
print(df.describe(), "\n")

# -----------------------------------
# 3. Check & handle missing values
# -----------------------------------
print("❓ Missing values in each column:\n")
print(df.isnull().sum(), "\n")

# Example handling:
# - If Quantity or UnitPrice is missing, drop those rows
# - If Product is missing, also drop those rows (you can change this logic)
df_clean = df.dropna(subset=["Product", "Quantity", "UnitPrice"])

print("✅ After dropping rows with missing Product/Quantity/UnitPrice:")
print(f"Rows before: {len(df)}, Rows after: {len(df_clean)}\n")

# -----------------------------------
# 4. Create Total Sales column
#    TotalSales = Quantity * UnitPrice
# -----------------------------------
df_clean["TotalSales"] = df_clean["Quantity"] * df_clean["UnitPrice"]

print("🧮 Added 'TotalSales' column (Quantity * UnitPrice):\n")
print(df_clean[["Product", "Quantity", "UnitPrice", "TotalSales"]].head(), "\n")

# -----------------------------------
# 5. Calculate overall total sales
# -----------------------------------
total_sales = df_clean["TotalSales"].sum()
print(f"💰 Overall Total Sales: {total_sales:.2f}\n")

# -----------------------------------
# 6. Find best-selling product
#    (based on highest total sales amount)
# -----------------------------------
product_sales = df_clean.groupby("Product")["TotalSales"].sum()

# Sort descending and get top 1
best_product = product_sales.idxmax()
best_product_sales = product_sales.max()

print("🏆 Total sales by product:\n")
print(product_sales.sort_values(ascending=False), "\n")

print(f"🏆 Best-Selling Product: {best_product}")
print(f"   Total Sales for {best_product}: {best_product_sales:.2f}\n")

# -----------------------------------
# 7. Create a basic text report
# -----------------------------------
print("========== 📘 SALES REPORT 📘 ==========")
print(f"Total number of orders     : {len(df_clean)}")
print(f"Number of unique products  : {df_clean['Product'].nunique()}")
print(f"Overall total sales (₹)    : {total_sales:.2f}")
print("---------------------------------------")
print(f"Best-selling product       : {best_product}")
print(f"Sales generated by it (₹)  : {best_product_sales:.2f}")
print("=======================================\n")